### ISSUE TITLE
Direction of the project

### ISSUE THREAD

**Issue by MarcusAndreasSvensson** [dylanebert/gsplat.js#24]
Hey,

I'm currently playing around with this implementation and one of the things I really enjoy is the API, how familiar it is when you have previously worked with Three.js.

I'm curious about the general goal and direction of this project. 
Seeing as this is built similarly to Three.js it would make sense (and pretty low friction) to provide an interface between meshes and splats, but I see no dependency to three in the project.

Is the goal to keep this as its own separate thing or do you have thoughts of integration into other libs?

**Comment by dylanebert** [comment]
Hello! My original goal with this library is a very lightweight gaussian viewer wrapper so that I can plug it into [gradio](https://github.com/gradio-app/gradio) and enable a gaussian splatting viewing on machine learning demos. It has a grown from there, but I think focusing on solely gaussian splatting makes sense for this library.

An advantage of having no three.js dependency is that this library is very lightweight, only [213Kb](https://www.npmjs.com/package/gsplat) unpacked, where three.js is [31.3Mb](https://www.npmjs.com/package/three) unpacked.

I think the [mkkellogg library](https://github.com/mkkellogg/GaussianSplats3D) will suit your needs better if you want to mix splatting with traditional rendering in a larger project.

**Comment by dylanebert** [comment]
It sounds like a good idea to me! If someone figures out how to keep this library fast and lightweight, with plugging it into other libraries, I definitely wouldn't be opposed.
